"""
Reaction engine for the Cartouche Bot Service.
Handles bot reactions to posts and other content.
"""
import logging
import random
from typing import Dict, List, Any, Optional
from datetime import datetime

from models import Post, Reaction
from config import settings

logger = logging.getLogger(__name__)

class ReactionEngine:
    """Engine for generating bot reactions to content."""
    
    def __init__(self):
        """Initialize the reaction engine."""
        pass
    
    def process_post_reactions(self, post: Post, bots: List[Dict[str, Any]]) -> List[Reaction]:
        """
        Process reactions to a post from multiple bots.
        
        Args:
            post: Post to react to
            bots: List of bot dictionaries
            
        Returns:
            List of reactions
        """
        reactions = []
        
        for bot in bots:
            # Skip if the bot is the author of the post
            if post.bot_id and post.bot_id == bot.get('id'):
                continue
            
            # Determine actions based on probability
            should_like = self._should_like_post(bot, post)
            should_comment = self._should_comment_on_post(bot, post)
            should_repost = self._should_repost_post(bot, post)
            
            # Process like
            if should_like:
                reaction = Reaction(
                    bot_id=bot.get('id'),
                    post_id=post.id,
                    reaction_type="like",
                    timestamp=datetime.now()
                )
                reactions.append(reaction)
            
            # Process comment
            if should_comment:
                # Comment content will be generated by LLM service
                reaction = Reaction(
                    bot_id=bot.get('id'),
                    post_id=post.id,
                    reaction_type="comment",
                    content=None,  # Will be filled by LLM service
                    timestamp=datetime.now()
                )
                reactions.append(reaction)
            
            # Process repost
            if should_repost:
                reaction = Reaction(
                    bot_id=bot.get('id'),
                    post_id=post.id,
                    reaction_type="repost",
                    timestamp=datetime.now()
                )
                reactions.append(reaction)
        
        return reactions
    
    def _should_like_post(self, bot: Dict[str, Any], post: Post) -> bool:
        """
        Determine if a bot should like a post based on probability.
        
        Args:
            bot: Bot data
            post: Post data
            
        Returns:
            Boolean indicating whether the bot should like the post
        """
        # Base probability from bot's characteristics
        base_probability = bot.get("like_probability", 0.5)
        
        # Adjust based on bot category
        category_adjustment = 0
        categories = bot.get("category", [])
        
        if "fan" in categories:
            category_adjustment += 0.3
        if "hater" in categories:
            category_adjustment -= 0.3
        if "neutral" in categories:
            category_adjustment += 0.0  # No change
        if "silent" in categories:
            category_adjustment -= 0.1
        
        # Adjust based on post content length
        content_adjustment = 0
        if len(post.content) > 200:
            content_adjustment += 0.05  # Slightly more likely to like longer posts
        
        # Calculate final probability
        final_probability = base_probability + category_adjustment + content_adjustment
        
        # Ensure probability is within valid range [0, 1]
        final_probability = max(0.0, min(1.0, final_probability))
        
        # Make decision based on probability
        return random.random() < final_probability
    
    def _should_comment_on_post(self, bot: Dict[str, Any], post: Post) -> bool:
        """
        Determine if a bot should comment on a post based on probability.
        
        Args:
            bot: Bot data
            post: Post data
            
        Returns:
            Boolean indicating whether the bot should comment on the post
        """
        # Base probability from bot's characteristics
        base_probability = bot.get("comment_probability", 0.2)
        
        # Adjust based on bot category
        category_adjustment = 0
        categories = bot.get("category", [])
        
        if "fan" in categories:
            category_adjustment += 0.2
        if "hater" in categories:
            category_adjustment += 0.2  # Haters also like to comment
        if "neutral" in categories:
            category_adjustment += 0.0  # No change
        if "silent" in categories:
            category_adjustment -= 0.15  # Silent bots comment less
        if "humorous" in categories:
            category_adjustment += 0.3  # Humorous bots comment more
        if "provocative" in categories:
            category_adjustment += 0.3  # Provocative bots comment more
        
        # Adjust based on post content length
        content_adjustment = 0
        if len(post.content) > 100:
            content_adjustment += 0.1  # More likely to comment on substantial posts
        
        # Calculate final probability
        final_probability = base_probability + category_adjustment + content_adjustment
        
        # Ensure probability is within valid range [0, 1]
        final_probability = max(0.0, min(1.0, final_probability))
        
        # Make decision based on probability
        return random.random() < final_probability
    
    def _should_repost_post(self, bot: Dict[str, Any], post: Post) -> bool:
        """
        Determine if a bot should repost a post based on probability.
        
        Args:
            bot: Bot data
            post: Post data
            
        Returns:
            Boolean indicating whether the bot should repost the post
        """
        # Base probability (reposting is less common than liking)
        base_probability = bot.get("repost_probability", 0.1)
        
        # Adjust based on bot category
        category_adjustment = 0
        categories = bot.get("category", [])
        
        if "fan" in categories:
            category_adjustment += 0.15
        if "hater" in categories:
            category_adjustment -= 0.05
        if "neutral" in categories:
            category_adjustment += 0.0  # No change
        if "silent" in categories:
            category_adjustment -= 0.08  # Silent bots repost less
        
        # Calculate final probability
        final_probability = base_probability + category_adjustment
        
        # Ensure probability is within valid range [0, 1]
        final_probability = max(0.0, min(1.0, final_probability))
        
        # Make decision based on probability
        return random.random() < final_probability
